### ISSUE TITLE
Enregistrer un sonore de sécurité

### ISSUE THREAD

**Issue by mathieumd** [dascritch/fmr-airtime#9]
Si aucun fichier son n'est accessible, [le script LS](/dascritch/fmr-airtime/blob/master/ansible_playbook/roles/fmr-airtime/templates/liquidsoap_fmr.liq.j2#L53) se rabat sur un son de sécurité.

Il faut donc enregistrer `securite_fmr.ogg` (à moins qu'il n'en existe déjà un ?) et l'inclure dans le playbook Ansible pour le déployer sur le disque système.

**Comment by dascritch** [comment]
Le 12/01/2015 14:33, Mathieu MD a écrit :
>
> Si aucun fichier son n'est accessible, le script LS
> </dascritch/fmr-airtime/blob/master/ansible_playbook/roles/fmr-airtime/templates/liquidsoap_fmr.liq.j2#L53>
> se rabat sur un son de sécurité.
>
> Il faut donc enregistrer |securite_fmr.ogg| (à moins qu'il n'en existe
> déjà un ?) et l'inclure dans le playbook Ansible pour le déployer sur
> le disque système.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dascritch/fmr-airtime/issues/9>.
>
On pourrait, mais pourquoi s'emmmerder  ? S'il n'y a pas de sons, il n'y
a pas de sons
Sinooooon http://www.radio-fmr.net/S/25ans/Macha.html

**Comment by mathieumd** [comment]
OK then.
